SADXModLoader/IniFile.cpp
SADXModLoader/IniFile.hpp

std::unordered_map doesn't have a reverse_iterator class. It never did, and it makes no sense, since it's an *unordered* map. However, MSVC 2013 (and possibly earlier versions) incorrectly provided a reverse_iterator class. MSVC 2015 removes it, which breaks IniFile.
Nothing actually makes use of the reverse_iterator functions, so simply removing them mostly fixes the MSVC 2015 build. There's another issue where printf() and scanf() functions were all inlined in MSVC 2015's CRT headers, which breaks the build because d3dx8.lib uses sprintf(). Adding legacy_stdio_definitions.lib fixes this, but that requires MSVC 2015.

Remove usage of std::unordered_map<>::reverse_iterator.

---

SADXModLoader/TextureReplacement.cpp
SADXModLoader/stdafx.h

d3dx8.lib depends on sprintf(), but Microsoft decided to inline most of the printf() and scanf() functions in the MSVC 2015 runtime. To fix this, we have to link in legacy_stdio_definitions.lib.
Reference: https://msdn.microsoft.com/en-us/library/Bb531344.aspx

MSVC 2015: Link in legacy_stdio_definitions.lib to fix undefined reference to _sprintf.

---

SADXModLoader/FixFOV.cpp

The pause menu would appear off-centered when in a "widescreen" resolution, due to the fact that the game assumes there will always be a 4:3 resolution, and thus uses the horizontal stretch value in place of the vertical stretch value (despite actually having the vertical stretch in memory?). 
The way to fix this is to just change the address that is referenced from 008928C0 (horizontal stretch) to 008928C4 (vertical stretch) in the set of instructions used for calculating the y-coordinates of the separate pause menu pieces.

Fixed widescreen pause menu positioning

---

SADXModLoader/MediaFns.cpp
SADXModLoader/dllmain.cpp
SADXModLoader/stdafx.h
libmodutils/GameObject.cpp

This PR has some minor fixes from MSVC 2017's code analysis tool. It also optimizes some string arrays by using char* and/or wchar_t* instead of string/wstring.
There's some more string optimizations that could be done by building filenames using swprintf() instead of wstring concatenation, but IniFile doesn't have constructors for char* or wchar_t* right now, so it wouldn't make sense to do that.
NOTE: This needs testing! I haven't been able to test the changes myself due to reasons.
Notable changes:
* GameObject now correctly sets the vtable function pointers. This specifically needs testing, since the pointers weren't set before.
* Use snprintf() instead of _snprintf(), since snprintf() is C99 compliant. (_snprintf() is still used on versions older than 2015.)
* Use unsigned loops …

MSVC 2017 analysis fixes

---

CHANGES.md
README.md
SADXModLoader/AutoMipmap.cpp
SADXModLoader/FileMap.cpp
SADXModLoader/FileMap.hpp
SADXModLoader/FileReplacement.cpp
SADXModLoader/FileSystem.cpp
SADXModLoader/FileSystem.h
SADXModLoader/MediaFns.cpp
SADXModLoader/MediaFns.hpp
SADXModLoader/SADXModLoader.rc
SADXModLoader/TextureReplacement.cpp
SADXModLoader/UiScale.cpp
SADXModLoader/dllmain.cpp
SADXModLoader/resource.h
SADXModLoader/stdafx.h
appveyor.yml
libmodutils/AnimationFile.h
libmodutils/GameObject.h
libmodutils/LandTableInfo.cpp
libmodutils/LandTableInfo.h
libmodutils/ModelInfo.cpp
libmodutils/ModelInfo.h
libmodutils/Trampoline.cpp
libmodutils/Trampoline.h

This PR has a bunch of improvements to various areas. Among other things, the PVR/PVM/GBIX blacklist code now uses more efficient data structures, which improve lookup performance (PVR/PVM now uses a binary search instead of linear; GBIX uses an unordered_set hash lookup instead of linear) and reduces data size (the text arrays are now C string arrays instead of vector<string>).
Other changes include using snprintf()/swprintf() to concatenate strings in many areas instead of C++ strings, which reduces memory allocations.
These changes need testing before merging, since they have the potential to break something. I did some quick tests by starting the program on Wine and Windows 7 and it seems to work, but I don't have any mods installed at the moment.
I also went through the commit log …

Various improvements, including a ~30k code size reduction.

---

SADXModLoader/AutoMipmap.cpp
SADXModLoader/Events.cpp
SADXModLoader/FixFOV.cpp
SADXModLoader/SADXModLoader.vcxproj
SADXModLoader/TextureReplacement.cpp
SADXModLoader/UiScale.cpp
SADXModLoader/include/MemAccess.h
libmodutils/libmodutils.vcxproj

MSVC 2017 (and 2015) have problems using thread-local storage on Windows XP. This showed up when using FunctionPointer() inside of a function where the argument is the result from Trampoline::Target(), since it needs TLS access here. It also caused a problem with a `static const string` within a function.
Solutions:
1. New macro NonStaticFunctionPointer() that works like FunctionPointer() but isn't static.
2. Changed the `static const string` to `static const char[]`.
This fixes SADX on my Windows XP VM.
This bug was reported by @PiKeyAr in #x-hax.
EDIT: A similar bug was reported for wxWidgets: https://trac.wxwidgets.org/ticket/17403
EDIT 2: This was introduced in MSVC 2015: https://docs.microsoft.com/en-us/cpp/build/reference/zc-threadsafeinit-thread-safe-local-static-initialization - …

Fix crashes on Windows XP.

---

SADXModManager/MainForm.cs
SADXModManager/MainForm.designer.cs

Windows 7's default fonts don't have U+2912 ('⤒') or U+2913 ('⤓'). This PR switches those two buttons to use Cambria on Windows 7 and earlier.
NOTE: Cambria was introduced on Windows Vista, so the buttons are still broken on Windows XP.
In addition, MainForm's font is now set to the Message Box font, which matches the OS default dialog font. This is a better font than Microsoft Sans Serif. I didn't apply this to any other forms yet due to layout issues.
This fixes issue #38. (Incompatible symbols in the Mod Manager (Windows 7))

MainForm: Fix top/bottom arrow buttons on Windows 7.

---

SADXModLoader/dllmain.cpp
SADXModLoader/include/MemAccess.h
SADXModLoader/include/SADXFunctions.h

Here's some minor optimizations.
* Use `uint8_t` for single-byte WriteData functions. This eliminates some warnings when writing bytes >= 0x80.
* Changed DisplayHintText's `strings` parameter to `const char *const *`.
* dllmain.cpp: Use Unicode strings where possible. Also, clear the errors vector when we're done using it.

Minor optimizations

---

SADXModLoader/dllmain.cpp

This prevents SADX from hanging when pressing Alt or F10. Alt+F2, Alt+F4 and Alt+Enter etc. functionality is still intact.

Ignore WM_SYSKEYDOWN and WM_SYSKEYUP in WndProc

---

SADXModLoader/dllmain.cpp

I'm terribly sorry for breaking this earlier. Alt+F4 should now work when the Input Mod is enabled and the Resizable Window option is disabled.

Correct handling of Alt+F4 for non-resizable wndProc

---

data/Codes.lst

Replaced the "Disable Music" code to set the `Music_Enabled` value to 0. This also disables music in Adventure Fields. Fixes #54

Update "Disable Music" code

---

SADXModLoader/hudscale.cpp
SADXModLoader/include/SADXStructsNew.h
SADXModLoader/uiscale.cpp
SADXModLoader/uiscale.h

This commits add the following UI elements (mentioned in #8) to the scaling system:
- Garden HUD
- Race HUD
- Monitor menu
- Black Market menu _(items can be scaled incorrectly or disappear, their code is very bad and will need to be rewritten.)_
- Entrance menu _(the message bar shows fine between 4:3 and 16:9, but the horizontal scaling is incorrect.)_
- Transporter menu
It also adds the following function to the scaled hooks:
- _chDrawBillboardSR_: a chao-specific rectangle drawing function (used for the Entrance, Transporter & monitor.)
- _chCalcWorldPosFromScreenPos_: a function that converts a 2D screen position to 3D coordinates (to place items and chao correctly in Black Market, Entrance and Transporter).
Misc:
- Little clean up, chao HUDs in a separate function for clarity.
- …

Chao HUDs Scaling

---

SADXModLoader/SADXModLoader.vcxproj
SADXModLoader/SADXModLoader.vcxproj.filters
SADXModLoader/dllmain.cpp
SADXModLoader/hudscale.cpp
SADXModLoader/include/SADXModInfo.h
SADXModLoader/include/ScaleInfo.h
SADXModLoader/uiscale.cpp
SADXModLoader/uiscale.h

This puts the needed functions for scaling HUDs outside of the mod loader in HelperFunctions.
What do you think? I made a copy of the scaling enums to avoid having to include `uiscale.h`, I don't know if that's appropriate.

Export scaling system

---

SADXModLoader/SADXModLoader.vcxproj
SADXModLoader/SADXModLoader.vcxproj.filters
SADXModLoader/dllmain.cpp
SADXModLoader/include/SADXFunctions.h
SADXModLoader/include/SADXVariables.h
SADXModLoader/testspawn.cpp
SADXModLoader/testspawn.h

This PR brings the [TestSpawn](https://github.com/sonicretro/sadx-test-spawn) mod by @michael-fadely directly into the Mod Loader.
Additions:
- `--save` command to load a specific save file. Usage: `--save 12`.
- `--no-music`, `--no-voice`, `--no-sound` and `no-audio` commands as suggested [here](https://github.com/sonicretro/sadx-test-spawn/issues/2).

TestSpawn implementation

---

SADXModLoader/SADXModLoader.vcxproj
SADXModManager/MainForm.cs
SADXModManager/Properties/Resources.Designer.cs
SADXModManager/Properties/Settings.Designer.cs
SADXModManager/SADXModManager.csproj
SADXModManager/app.config
SADXModManager/packages.config

This pull request upgrades the Mod Manager and its mod-loader-common submodule to .NET Framework 4.8.
Small fix meant for the master branch: Vanilla Config Editor's gamepad settings not being saved if the `Save` button was clicked in the main window.

.NET Framework 4.8 upgrade

---

SADXModLoader/dllmain.cpp
SADXModManager/LoaderInfo.cs
SADXModManager/MainForm.cs
SADXModManager/MainForm.designer.cs

A modification from the lantern engine was pushed [(commit)](https://github.com/X-Hax/sadx-mod-loader/commit/209705ff7a24fa162380aa03d79c471551a25072) to be included inside the mod loader itself, changing how vertex colors were shaded - also deviating from how the vanilla game functions. The speedrun community would rather have the option to disable this modification as it impacts the run in certain things such as jungle visibility.

Added Disable PolyBuff code

---

SADXModLoader/SADXModLoader.vcxproj
SADXModLoader/SADXModLoader.vcxproj.filters
SADXModLoader/SkyChaseFixes.cpp
SADXModLoader/SkyChaseFixes.h
SADXModLoader/hudscale.cpp

The Sky Chase fix originally developed for Dreamcast Conversion and SADXFE changes Sky Chase control sensitivity, enemy detection range, reticle scale and score calculation at different resolutions to behave more like they would at the game's original resolution of 640x480. This is a "lite" version of the fix that makes only the minimum required changes and doesn't touch other things such as lighting or the skybox. Only one drawing function call was hooked to fix the scale of the locked-on reticle.
The fix is compatible with the versions of it included in SADXFE and Dreamcast Conversion. As it is added as part of the UI Scaling option, it can be disabled using the "UI Scaling" toggle.

Integrate the Sky Chase fix

---

SADXModLoader/TextureReplacement.cpp
SADXModLoader/TextureReplacement.h
SADXModLoader/dllmain.cpp
SADXModLoader/include/SADXModInfo.h

This will allow users to place texture packs in their mods in a `replacetex` folder that will enable them to override individual textures in any PVM/Texture Pack/PVMX file that comes before it in the mod order.
There is a slight issue where files that were renamed from the base game files and use the .pvm.prs extension (such as Dreamcast Conversion's textures) won't correctly report the mod index, thus always being replaced, but that mod's usually pretty early in the mod order anyway.

Support For Individual Texture Replacements

---

SADXModLoader/direct3d.cpp
SADXModLoader/dllmain.cpp
SADXModLoader/polybuff.cpp
SADXModLoader/polybuff.h

This PR reverts changes made to the memory pool and locking method used by the polybuff subsystem. When window resizing was implemented, they were changed in a ham-fisted manner (by me!) to use the managed memory pool before the polybuff system was fully reverse engineered. Now that the polybuff system is effectively completely known, it has become clear that these changes were unnecessary.
When a device reset occurs (window resize, fullscreen toggle, etc), the polybuff system is simply finalized and re-initialized with no adverse effects. Mods with large numbers of animated meshes (i.e. Beta Windy Valley) see significant performance gains with this change.

Fix polybuff performance when window resize is enabled

---

SADXModLoader/SADXModLoader.vcxproj
SADXModLoader/SADXModLoader.vcxproj.filters
SADXModLoader/backend.cpp
SADXModLoader/backend.h
SADXModLoader/config.cpp
SADXModLoader/dllmain.cpp
SADXModLoader/include/SADXModInfo.h

**Description**
This PR adds a `RenderBackend` (int) option to Graphics settings in the loader JSON file. The following values are usable at the moment:
0 - DirectX 8.1 (default)
1 - DirectX 9 via d3d8to9
**Implementation**
When the backend value is set to 1, the Mod Loader loads the file `d3d8m.dll` from the extlibs folder using `LoadLibraryEx` and hooks the game's function `Direct3DCreate8` to make it return d3d8to9's Direct3D object instead.
**Some notes**
- `d3d8.dll` in the game folder is no longer required to load d3d8to9.
- This hack is completely transparent to the game and mods, including Lantern Engine, which will detect d3dto9 correctly without any modifications.
- If it finds `d3d8.dll` in the game folder, it will assume d3d8to9 is already loaded and do nothing, so the old …

Add "Render Backend" config option, allow to load d3d8to9 without placing d3d8.dll in game directory

---

SADXModLoader/polybuff.cpp

As noticed by PkR, the current rewrite of "polybuff" functions lacking vertex color support is causing performance issues.
We narrowed it down to this part, which differs from the vanilla implementation:
```
*head = *(head + 1);
*buffer = *(buffer - 1);
``` 
Going back and forth likely causing memory overhead.
This PR rewrites these parts to be closer to vanilla, and also cleans up the IDA-pasted code.

Improve performance of triangle strips with vertex colors

---

SADXModLoader/hudscale.cpp
SADXModLoader/include/SADXFunctionsNew.h
SADXModLoader/uiscale.cpp

Currently uiscale is applied to the whole pause menu loop, which itself contains two additional loops (for the control and camera menus). The problem is that the game runs DisplayAllObjects inside each of these loops, so all task displays are UI scaled to the center.
To circumvent this, SF made task displayers run in auto scale mode while paused, but it means that uiscale is always active while paused. This presents a problem for mods that are rendering without uiscale, or that rewrite DisplayAllObjects (Multiplayer mod in both cases).
I replaced the hack with other hacks that leave DisplayAllObjects unscaled.
The only problem is that I had to do some magic for the camera and control menus, so mods won't be able to rewrite them directly. Another solution is to hack the …

Improve uiscale in pause menu
